### ISSUE TITLE
Please bump `containers` upperbound

### ISSUE THREAD

**Issue by ezzieyguywuf** [haskell-distributed/network-transport-inmemory#25]
I have successfully compiled with `containers-0.6.2.1` and `ghc-8.10.3`. Things compile and tests pass.

If you are able to make this change and release a new version, it will allow us to better package this project in gentoo.

**Comment by ezzieyguywuf** [comment]
Based on a conversation in IRC, we've decided to remove this package from gentoo. Closing this ticket.

**Comment by facundominguez** [comment]
Hello @ezzieyguywuf. Noted. Please, let me know if any other request comes up.
